Django Backend/electoraldb/electoraldb/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'electoraldb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^electoraldb/', include('electoraldbapp.urls')),
)

urlpatterns += staticfiles_urlpatterns()

Django Backend/electoraldb/nish/urls.py
from django.conf.urls import patterns,url
from electoraldbapp import views
from django.views.generic.base import TemplateView

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	# url(r'^home/', TemplateView.as_view(template_name='electoraldb/base.html'),
	url(r'^add_address/$', views.add_address, name='add_address'),
	url(r'^add_voter/$', views.add_voter, name='add_voter'),
	url(r'^town_from_pin/$',views.get_towns_from_pincode, name='town_from_pin')
	)

Django Backend/electoraldb/nishkarsh/part1/pre-ajax/talk_project/talk_project/urls.py
from django.conf.urls import patterns, include, url
from talk_project.views import logout_page

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    url(r'^', include('talk.urls')),
)

Django Backend/electoraldb/rahul/myelectoral_project/myelectoral_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'electoraldb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^electoraldb/', include('electoraldbapp.urls')),
)

urlpatterns += staticfiles_urlpatterns()

Django Backend/electoraldb/nish/models.py
from __future__ import unicode_literals

from django.db import models


class Address(models.Model):
    pin = models.IntegerField(db_column='PIN')  # Field name made lowercase.
    po = models.CharField(db_column='PO', max_length=20)  # Field name made lowercase.
    town = models.CharField(db_column='Town', max_length=50)  # Field name made lowercase.
    district = models.CharField(db_column='District', max_length=50)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=50)  # Field name made lowercase.
    acno = models.CharField(db_column='ACno', max_length=10, blank=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Address'


class Candidate(models.Model):
    candidateid = models.CharField(db_column='Candidateid', primary_key=True, max_length=10)  # Field name made lowercase.
    voterid = models.CharField(db_column='Voterid', max_length=10)  # Field name made lowercase.
    acno = models.CharField(db_column='Acno', max_length=10)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=3)  # Field name made lowercase.
    partyid = models.CharField(db_column='Partyid', max_length=10, blank=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=60)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Candidate'


class Constituency(models.Model):
    acno = models.CharField(db_column='Acno', primary_key=True, max_length=10)  # Field name made lowercase.
    acname = models.CharField(db_column='Acname', max_length=50)  # Field name made lowercase.
    population = models.IntegerField(db_column='Population', blank=True, null=True)  # Field name made lowercase.
    pcno = models.CharField(db_column='PCno', max_length=10, blank=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Constituency'


class DistrictConstituency(models.Model):
    district = models.CharField(db_column='District', max_length=50)  # Field name made lowercase.
    acno = models.CharField(db_column='Acno', max_length=10)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'District_Constituency'


class Election(models.Model):
    electionid = models.CharField(db_column='Electionid', primary_key=True, max_length=10)  # Field name made lowercase.
    year = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Election'


class ElectionStatistics(models.Model):
    electionid = models.CharField(db_column='Electionid', max_length=10)  # Field name made lowercase.
    partyid = models.CharField(db_column='Partyid', max_length=10)  # Field name made lowercase.
    stvotes = models.IntegerField(db_column='STVotes', blank=True, null=True)  # Field name made lowercase.
    scvotes = models.IntegerField(db_column='SCVotes', blank=True, null=True)  # Field name made lowercase.
    obcvotes = models.IntegerField(db_column='OBCVotes', blank=True, null=True)  # Field name made lowercase.
    genvotes = models.IntegerField(db_column='GENVotes', blank=True, null=True)  # Field name made lowercase.
    femalevotes = models.IntegerField(db_column='FemaleVotes', blank=True, null=True)  # Field name made lowercase.
    malevotes = models.IntegerField(db_column='MaleVotes', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Election_Statistics'


class Identity(models.Model):
    picno = models.CharField(db_column='PICno', primary_key=True, max_length=20)  # Field name made lowercase.
    pictype = models.CharField(db_column='PICtype', max_length=10)  # Field name made lowercase.
    pic = models.TextField(db_column='PIC', blank=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Identity'


class ParliamentaryConstituency(models.Model):
    pcno = models.CharField(db_column='PCno', primary_key=True, max_length=10)  # Field name made lowercase.
    pcname = models.CharField(db_column='PCName', max_length=50)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=50)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Parliamentary_Constituency'


class Party(models.Model):
    partyid = models.CharField(db_column='Partyid', primary_key=True, max_length=10)  # Field name made lowercase.
    partyname = models.CharField(db_column='PartyName', max_length=50)  # Field name made lowercase.
    symbol = models.TextField(db_column='Symbol', blank=True)  # Field name made lowercase.
    type = models.CharField(db_column='Type', max_length=10)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=50)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Party'


class PartyCandidate(models.Model):
    partyid = models.CharField(db_column='Partyid', max_length=10)  # Field name made lowercase.
    voterid = models.CharField(db_column='Voterid', max_length=10)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Party_Candidate'


class Polling(models.Model):
    partno = models.CharField(db_column='Partno', primary_key=True, max_length=11)  # Field name made lowercase.
    acno = models.CharField(db_column='Acno', max_length=10)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Polling'


class Relation(models.Model):
    voterid = models.CharField(db_column='Voterid', max_length=10)  # Field name made lowercase.
    relationvoterid = models.CharField(db_column='Relationvoterid', max_length=10)  # Field name made lowercase.
    relation = models.CharField(db_column='Relation', max_length=10)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Relation'


class Voter(models.Model):
    voterid = models.CharField(db_column='Voterid', primary_key=True, max_length=10)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=50)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=50) 
    age = models.IntegerField(db_column='Age')  # Field name made lowercase.
    gender = models.CharField(db_column='Gender', max_length=6)  # Field name made lowercase.
    dob = models.DateField(db_column='DOB')  # Field name made lowercase.
    doi = models.DateField(db_column='DOI', blank=True, null=True)  # Field name made lowercase.
    doa = models.DateField(db_column='DOA')  # Field name made lowercase.
    emailid = models.CharField(db_column='emailID', max_length=60)  # Field name made lowercase.
    phoneno = models.IntegerField(db_column='Phoneno')  # Field name made lowercase.
    picno = models.CharField(db_column='PICno', max_length=20, blank=True)  # Field name made lowercase.
    houseno = models.CharField(db_column='Houseno', max_length=10)  # Field name made lowercase.
    streetno = models.CharField(db_column='Streetno', max_length=20)  # Field name made lowercase.
    town = models.CharField(db_column='Town', max_length=50)  # Field name made lowercase.
    pin = models.IntegerField(db_column='PIN')  # Field name made lowercase.
    caste = models.CharField(db_column='Caste', max_length=3)  # Field name made lowercase.
    partno = models.CharField(db_column='Partno', max_length=11)  # Field name made lowercase.
    approved = models.CharField(db_column='Approved', max_length=5, blank=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=50)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Voter'

Django Backend/electoraldb/nish/forms.py
from django import forms
from electoraldbapp.models import Address, Constituency, Voter, Polling, Party
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime
import html5.forms.widgets as html5_widgets

forms.DateInput.input_type="date"
forms.DateTimeInput.input_type="datetime-local" 
def encode(t):
	s = str(t)
	for i in range(0,8-len(s)):
		s = "0"+s
	return s

class AddressForm(forms.ModelForm):
	pin = forms.IntegerField(help_text="Please enter the pincode",required=False)# Field name made lowercase.
	po = forms.CharField(max_length=20,help_text="Post office?")  # Field name made lowercase.
	town = forms.CharField(max_length=50,help_text="Town?")  # Field name made lowercase.
	district = forms.CharField(max_length=50,help_text="District?")  # Field name made lowercase.
	state = forms.CharField(max_length=50,help_text="state?")  # Field name made lowercase.
	acno = forms.ModelChoiceField(queryset=Constituency.objects.all(),help_text="Select the constituency")  # Field name made lowercase.
	key = forms.CharField(help_text="What is your aim?")
	class Meta:
		model = Address
		fields = ('pin','po','town','district','state','acno',)
	#  	
class VoterForm(forms.ModelForm):
	name = forms.CharField(max_length=50,help_text="Enter your name:")
    password = forms.CharField(widget=forms.PasswordInput())
	# Field name made lowercase.
	age = forms.IntegerField(validators=[MinValueValidator(18)],help_text="Enter your age")  # Field name made lowercase.
	gender = forms.ChoiceField(label=u'sex', choices=[('Male','Male'),('Female','Female'),('Other','Other')], widget=forms.Select(), required=False,help_text="Enter your gender:")
	pin = forms.CharField(max_length = 30,help_text = "fill this one")
	town = forms.CharField(max_length = 30,help_text = "fill this one for town")
	dob = forms.DateField(help_text="Birth Date:")  # Field name made lowercase.
	emailid = forms.EmailField(max_length=100,help_text="Enter your emailid:")  # Field name made lowercase.
	phoneno = forms.IntegerField(help_text="Enter your phoneno:")  # Field name made lowercase.
	houseno = forms.IntegerField(help_text="Enter your houseno:")  # Field name made lowercase.
	streetno = forms.CharField(max_length=20,help_text="Enter your streetno:")  # Field name made lowercase.
	#pin = forms.ModelChoiceField(queryset=Address.objects.all(),help_text="Select your pin code:")  # Field name made lowercase.
	#town = forms.ModelChoiceField(queryset=Address.objects.all(),help_text="Select your town:")  # Field name made lowercase.
	caste = forms.ChoiceField(label='Caste',choices=[('ST','Scheduled Tribe'),('SC','Scheduled Caster'),('OBC','Other Backward Classes'),('GEN','General')],help_text="Enter your caste:")  # Field name made lowercase.
	#partno = forms.CharField(initial = 0,help_text="Part no")
	# def clean(self):
	# 	dob = self.cleaned_data['dob']
	# 	today = datetime.date.today()
	# 	if (dob.year + 18, dob.month, dob.day) > (today.year, today.month, today.day):
	# 		raise forms.ValidationError('Must be at least 18 years old to register')
	# 	return dob
	class Meta:
		model = Voter
		fields = ('name','age','gender','dob','emailid','phoneno','houseno','streetno','caste')
		#exclude = ('voterid','doa','doi','picno','partno',)

Django Backend/electoraldb/templates/electoraldb/add_address.html
<!DOCTYPE html>
<html>
    <head>
        <title>Electoral Db</title>
    </head>

    <body>
        <h1>Add an address</h1>

        <form id="address_form" method="post" action="/electoraldb/add_address/">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
                <br />
            {% endfor %}

            <input type="submit" name="submit" value="Create Category" />
        </form>
    </body>

</html>

Django Backend/electoraldb/templates/electoraldb/add_candidate.html
{%extends "electoraldb/base.html" %}
{% load staticfiles %}
{%block title%}Candidate Registration{%endblock%}
{%block head%}
<link href='/static/css/strength.css' rel='stylesheet' type='text/css'>
{%endblock%}
{%block content%}
<div class="container pull-left">
	<div class="row"> 
		<div class="col-sm-6 text-center">
			<h1>Candidate Registration Form</h1>
		</div>
	</div>

	<form id="candidate_form" class="form-horizontal" method="post" action="/electoraldb/validate_candidate/">
		{% csrf_token %}
		<div class="form-group">
			<label class="col-sm-2 control-label">Voterid:</label>
			<div class="col-sm-4">
				<input class="form-control" id="id_voterid" maxlength="10" name="voterid" type="text" placeholder="Enter your Voter ID" required/>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">AC Number:</label>
			<div class="col-sm-4">
				<select class="form-control" id="id_acno" name="acno">
					<!-- Print the list here -->
					{%for ac in acno%}<option value="{{ac}}">{{ac}}</option>{%endfor%}
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Type:</label>
			<div class="col-sm-4">
				<select class="form-control" id="id_type" name="type">
					<option value="MP">MP</option>
					<option value="MLA">MLA</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Party ID:</label>
			<div class="col-sm-4">
				<select class="form-control" id="id_partyid" name="partyid"><option value="NO Party">NO Party</option>{%for id in pid%}<option value="{{id}}">{{id}}</option>{%endfor%}
				</select>
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-2 control-label">Password:</label>
			<div class="col-sm-4">
				<div class="input-group">
					<input class="form-control" id="id_password" name="password" type="password" placeholder="Enter the Password" required/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Confirm Password:</label>
			<div class="col-sm-4">
				<div>
					<input class="form-control" id="id_re_password" name="re_password" type="password" placeholder="Confirm Password" required/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-2">
				<input id="submit-btn" class="form-control btn btn-primary" type="submit" name="submit" value="Add Candidate" />
			</div>
		</div>
	</form>
</div>
{%endblock%}
{%block scripts%}
<script type="text/javascript" src="/static/js/strength.js"></script>
<script type="text/javascript">
$(document).ready(function ($) {
     $('input#id_password').strength({
 		strengthClass: 'strength',
        strengthMeterClass: 'strength_meter input-group-addon',
        strengthButtonClass: 'button_strength',
        strengthButtonText: 'Show password',
        strengthButtonTextToggle: 'Hide Password'});
});
// submit button clicked
$('#candidate_form').submit(function(){
	if($('input#id_re_password').val() == $('input#id_password').val() && $('input#id_password').val()!="")
	{
		$("input#id_re_password").parent().html("");
		return true;
	}
	else
	{
		alert("Password Mismatch");
		return false;
	}
});
// Confirm Password
$('input#id_password').on('input propertychange paste', function() {
	// check if re password is same as password
	// alert('changed!');
	if($('input#id_re_password').val() != $('input#id_password').val() || $('input#id_password').val()=="")
	{
		// unsuccessful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-error');
	}
	else
	{
		//successful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-success');
	}
});
$('input#id_re_password').on('input propertychange paste', function() {
	// check if re password is same as password
	// alert('changed!');
	if($('input#id_re_password').val() != $('input#id_password').val() || $('input#id_password').val()=="")
	{
		// unsuccessful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-error');
	}
	else
	{
		//successful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-success');
	}
});
</script>
{%endblock%}

Django Backend/electoraldb/templates/electoraldb/add_party.html
{%extends "electoraldb/base.html" %}
{% load staticfiles %}
{%block title%}Party Registration{%endblock%}
{%block head%}
<link href='/static/css/strength.css' rel='stylesheet' type='text/css'>
{%endblock%}
{%block content%}
<div class="container pull-left">
	<div class="row"> 
		<div class="col-sm-6 text-center">
			<h1>Party Registration Form</h1>
		</div>
	</div>
	<form id="party_form" class="form-horizontal" method="post" action="/electoraldb/validate_party/" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-group">
			<label class="col-sm-2 control-label">Party Name:</label>
			<div class="col-sm-4">
				<input class="form-control" id="id_partyname" maxlength="50" name="partyname" type="text" placeholder="Enter party name" required/>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Symbol:</label>
			<div class="col-sm-4">
				<input class="form-control" id="id_symbol" name="symbol" type="file" required/>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Type:</label>
			<div class="col-sm-4">
				<select class="form-control" id="id_type" name="type">
					<option value="national">National</option>
					<option value="state">State</option>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Password:</label>
			<div class="col-sm-4">
				<div class="input-group">
					<input class="form-control" id="id_password" name="password" type="password" placeholder="Enter the Password" required/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label">Confirm Password:</label>
			<div class="col-sm-4">
				<div>
					<input class="form-control" id="id_re_password" name="re_password" type="password" placeholder="Confirm Password" required/>
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-2">
				<input id="submit-btn" class="form-control btn btn-primary" type="submit" name="submit" value="Add Party" />
			</div>
		</div>
	</form>
</div>
{%endblock%}
{%block scripts%}
<script type="text/javascript" src="/static/js/strength.js"></script>
<script type="text/javascript">
$(document).ready(function ($) {
     $('input#id_password').strength({
 		strengthClass: 'strength',
        strengthMeterClass: 'strength_meter input-group-addon',
        strengthButtonClass: 'button_strength',
        strengthButtonText: 'Show password',
        strengthButtonTextToggle: 'Hide Password'});
});
// submit button clicked
$('#party_form').submit(function(){
	if($('input#id_re_password').val() == $('input#id_password').val() && $('input#id_password').val()!="")
	{
		$("input#id_re_password").parent().html("");
		return true;
	}
	else
	{
		alert("Password Mismatch");
		return false;
	}
});
// Confirm Password
$('input#id_password').on('input propertychange paste', function() {
	// check if re password is same as password
	// alert('changed!');
	if($('input#id_re_password').val() != $('input#id_password').val() || $('input#id_password').val()=="")
	{
		// unsuccessful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-error');
	}
	else
	{
		//successful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-success');
	}
});
$('input#id_re_password').on('input propertychange paste', function() {
	// check if re password is same as password
	// alert('changed!');
	if($('input#id_re_password').val() != $('input#id_password').val() || $('input#id_password').val()=="")
	{
		// unsuccessful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-error');
	}
	else
	{
		//successful
		$('input#id_re_password').parent().removeClass();
		$('input#id_re_password').parent().addClass('has-success');
	}
});
</script>
{%endblock%}

Django Backend/electoraldb/templates/electoraldb/candidate.html
{%extends "electoraldb/base.html" %}
{% load staticfiles %}
{%block title%}Welcome Candidate{%endblock%}

{%block content%}

{%if user.is_authenticated%}
<div class="container pull-left">
	<h2>Candidate Details:</h2>
	<table class="table table-striped">
		<tbody>
			<tr>
				<td>Candidate ID:</td>
				<td>{{candidate.candidateid}}</td>
			</tr>
			<tr>
				<td>AC Number:</td>
				<td>{{candidate.acno}}</td>
			</tr>
			<tr>
				<td>Type:</td>
				<td>{{candidate.type}}</td>
			</tr>
			<tr>
				<td>Party ID:</td>
				<td>{{candidate.partyid}}</td>
			</tr>
			{%ifnotequal party.partyid 'NO Party'%}
			<tr>
				<td>PartyID:</td>
				<td>{{party.partyid}}</td>
			</tr>
			<tr>
				<td>Party Name:</td>
				<td>{{party.partyname}}</td>
			</tr>
			<tr>
				<td>Party Symbol:</td>
				<td><img src="/static/media/{{party.symbol}}"></td>
			</tr>
			<tr>
				<td>Party Type:</td>
				<td>{{party.type}}</td>
			</tr>
			<tr>
				<td>Party Status:</td>
				<td><span class="label {%ifequal party.is_approved True%}label-success{%else%}label-danger{%endifequal%}">{{party.is_approved}}</span></td>
			</tr>
			{%endifnotequal%}
			<tr>
				<td>Candidature Status:</td>
				<td><span class="label {%ifequal candidate.is_approved True%}label-success{%else%}label-danger{%endifequal%}">{{candidate.is_approved}}</span></td>
			</tr>
			<tr>
				<td>VoterID:</td>
				<td>{{voter.voterid}}</td>
			</tr>
			<tr>
				<td>Name:</td>
				<td>{{voter.name}}</td>
			</tr>
			<tr>
				<td>Gender:</td>
				<td>{{voter.gender}}</td>
			</tr>
			<tr>
				<td>Date of Birth:</td>
				<td>{{voter.dob}}</td>
			</tr>
			<tr>
				<td>Date of Issue:</td>
				<td>{{voter.doi}}</td>
			</tr>
			<tr>
				<td>Date of Application</td>
				<td>{{voter.doa}}</td>
			</tr>
			<tr>
				<td>Email-ID:</td>
				<td>{{voter.emailid}}</td>
			</tr>
			<tr>
				<td>Phone No.:</td>
				<td>{{voter.phoneno}}</td>
			</tr>
			<tr>
				<td>House No.:</td>
				<td>{{voter.houseno}}</td>
			</tr>
			<tr>
				<td>Street No.:</td>
				<td>{{voter.streetno}}</td>
			</tr>
			<tr>
				<td>Town:</td>
				<td>{{voter.town}}</td>
			</tr>
			<tr>
				<td>PIN Code:</td>
				<td>{{voter.pin}}</td>
			</tr>
			<tr>
				<td>Caste</td>
				<td>{{voter.caste}}</td>
			</tr>
			<tr>
				<td>Voter Status:</td>
				<td><span class="label {%ifequal voter.approved "true"%}label-success{%else%}label-danger{%endifequal%}">{{voter.approved}}</span></td>
			</tr>
			{%ifequal voter.approved "true"%}
			<tr>
				<td>Part No.:</td>
				<td>{{voter.partno}}</td>
			</tr>
			{%endifequal%}
		</tbody>
	</table>
</div>
{%endif%}

{%endblock%}

Django Backend/electoraldb/templates/electoraldb/candidate_success.html
{%extends "electoraldb/base.html" %}
{% load staticfiles %}
{%block title%}Candidate Registration Successful{%endblock%}
{%block content%}
<div class="container">
	<h1>Viola!! You are registered</h1>
	<table class="table table-striped">
		<tbody>
			<tr>
				<td>Username :</td>
				<td>{%if Username%}{{Username}}{%endif%}</td>
			</tr>
			<tr>
				<td>Password :</td>
				<td>{%if Password%}{{Password}}{%endif%}</td>
			</tr>
		</tbody>
	</table>
</div>
{%endblock%}

Django Backend/electoraldb/templates/electoraldb/constituency.html
{%extends "electoraldb/base.html" %}
{% load staticfiles %}
{%block title%}Constituency Search{%endblock%}
{%block content%}
<div class="container pull-left">
	<a class="pull-right btn btn-primary" href="/electoraldb/query/">Back</a>
	<h2>Constituency Details:</h2>
	<table class="table table-striped">
		<tbody>
			<tr>
				<td>AC Number:</td>
				<td>{{constituency.acno}}</td>
			</tr>
			<tr>
				<td>AC Name:</td>
				<td>{{constituency.acname}}</td>
			</tr>
			<!-- <tr>
				<td>Population:</td>
				<td>{{constituency.population}}</td>
			</tr> -->
			<tr>
				<td>Pirliamentary Constituency Number:</td>
				<td>{{pconstituency.pcno}}</td>
			</tr>
			<tr>
				<td>Pirliamentary Constituency Name:</td>
				<td>{{pconstituency.pcname}}</td>
			</tr>
			<tr>
				<td>State:</td>
				<td>{{pconstituency.state}}</td>
			</tr>
			<tr>
				<td>Population:</td>
				<td>{{data.population}}</td>
			</tr>
			<tr>
				<td>Number of Male Voters:</td>
				<td>{{data.male}}</td>
			</tr>
			<tr>
				<td>Number of Female Voters:</td>
				<td>{{data.female}}</td>
			</tr>
			<tr>
				<td>Number of General Voters:</td>
				<td>{{data.gen}}</td>
			</tr>
			<tr>
				<td>Number of OBC Voters:</td>
				<td>{{data.obc}}</td>
			</tr>
			<tr>
				<td>Number of ST Voters:</td>
				<td>{{data.st}}</td>
			</tr>
			<tr>
				<td>Number of SC Voters:</td>
				<td>{{data.sc}}</td>
			</tr>
		</tbody>
	</table>
</div>
{%endblock%}

Django Backend/electoraldb/templates/electoraldb/header.html
{% extends "electoraldb/add_voter.html" %}
{% block head %}
<meta charset="utf-8">
<meta property="og:image" content="http://ianlunn.github.io/Hover/hover.jpg" />
<meta property="og:site_name" content="Hover.css"/>
<meta property="og:title" content="Hover.css - A collection of CSS3 powered hover effects" />
<!-- <link href="css/demo-page.css" rel="stylesheet" media="all"> -->
<link href="{% static 'css/hover.css' %}" rel="stylesheet" media="all">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="all">
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" media="all">
<style type="text/css">
.no_radius
{
	border-radius: 0px;
}
</style>
{% endblock %}